---
- name: Configure hadoop-env.sh
  template: src=hadoop-env.sh.j2 dest={{hdfs_conf_dir}}/hadoop-env.sh owner={{hdfs_user}} group={{hdfs_group}} mode=0755
  notify:
   - Restart namenode
   - Restart secondary namenode
   - Restart datanode
   - Restart journalnode
   - Restart zkfc
  tags:
   - hdfs-env
   - hdfs-log4j-config

- name: Configure core-site.xml
  template: src=core-site.xml.j2 dest={{hdfs_conf_dir}}/core-site.xml owner={{hdfs_user}} group={{hdfs_group}} mode=0755
  notify:
   - Restart namenode
   - Restart secondary namenode
   - Restart datanode
   - Restart journalnode
   - Restart zkfc
  tags:
   - hdfs-core-config

- name: Configure hdfs-site.xml
  template: src=hdfs-site.xml.j2 dest={{hdfs_conf_dir}}/hdfs-site.xml owner={{hdfs_user}} group={{hdfs_group}} mode=0755
  notify:
   - Restart namenode
   - Restart secondary namenode
   - Restart datanode
   - Restart journalnode
   - Restart zkfc
  tags:
   - hdfs-site-config

- name: Configure log4j.properties
  template: src=log4j.properties.j2 dest={{hdfs_conf_dir}}/log4j.properties owner={{hdfs_user}} group={{hdfs_group}} mode=0755
  notify:
   - Restart namenode
   - Restart secondary namenode
   - Restart datanode
   - Restart journalnode
   - Restart zkfc
  tags:
   - hdfs-log4j-config
