---
- name: Create datanode directories
  file: path={{item}} state=directory owner={{hdfs_user}} group={{hdfs_group}} mode={{ hdfs_dfs_datanode_data_dir_perm }} mode=0700
  with_items: "{{ hdfs_datanode_dir_list }}"

- name: Set program variable to 'datanode'
  set_fact: program="datanode"

- name: Deploy init.d service for datanode
  template: src=hdfs-service.j2 dest=/etc/init.d/hdfs-datanode owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for datanode
  template: src=hdfs.service.j2 dest=/lib/systemd/system/hdfs-datanode.service owner=root group=root mode=0644
  when: ansible_service_mgr == "systemd"

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd"
  changed_when: false

- name: Register datanode service
  service: name=hdfs-datanode enabled=yes
