---
- name: Add hadoop group on all machines
  group: name={{hdfs_group}} state=present

- name: Add hadoop user on first namenode only and generate an ssh key
  user: name={{hdfs_user}} comment="Hadoop superuser" uid=1040 group={{hdfs_group}} createhome=yes generate_ssh_key="{{ hdfs_ssh_fence }}"
  when: inventory_hostname == hdfs_namenodes[0]

- name: Create user on all machines
  user: name={{hdfs_user}} comment="Hadoop superuser" uid=1040 group={{hdfs_group}} home={{ hdfs_user_home }} createhome=yes
  register: created_user

- include: ssh_fence.yml
  when: hdfs_ssh_fence and inventory_hostname in hdfs_namenodes
